### ISSUE TITLE
lb4 not work before last update

### ISSUE THREAD

**Issue by fgvicente** [sourcefuse/loopback4-starter#49]
@samarpanB

 lb4 rest-crud

(node:4884) UnhandledPromiseRejectionWarning: Error: Cannot load  /home/fvicente/Proyectos/loopback4apps/new/marqfapp/src/datasources/auditdb.datasource.config.json: ENOENT: no such file or directory, open '/home/fvicente/Proyectos/loopback4apps/new/marqfapp/src/datasources/auditdb.datasource.config.json'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.exports.isConnectorOfType (/home/fvicente/.nvm/versions/node/v12.16.1/lib/node_modules/@loopback/cli/lib/utils.js:608:37)
    at /home/fvicente/.nvm/versions/node/v12.16.1/lib/node_modules/@loopback/cli/generators/rest-crud/index.js:163:28
    at Array.filter (<anonymous>)
    at RestCrudGenerator.promptDataSourceName (/home/fvicente/.nvm/versions/node/v12.16.1/lib/node_modules/@loopback/cli/generators/rest-crud/index.js:161:50)
(node:4884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

lb4 repository

(node:5049) UnhandledPromiseRejectionWarning: Error: Cannot load  /home/fvicente/Proyectos/loopback4apps/new/marqfapp/src/datasources/auditdb.datasource.config.json: ENOENT: no such file or directory, open '/home/fvicente/Proyectos/loopback4apps/new/marqfapp/src/datasources/auditdb.datasource.config.json'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.exports.isConnectorOfType (/home/fvicente/.nvm/versions/node/v12.16.1/lib/node_modules/@loopback/cli/lib/utils.js:608:37)
    at /home/fvicente/.nvm/versions/node/v12.16.1/lib/node_modules/@loopback/cli/generators/repository/index.js:262:28
    at Array.filter (<anonymous>)
    at RepositoryGenerator.promptDataSourceName (/home/fvicente/.nvm/versions/node/v12.16.1/lib/node_modules/@loopback/cli/generators/repository/index.js:260:50)
(node:5049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

lb4 discover
? Seleccione el conector que se va a descubrir (Use arrow keys)
❯ auditdb 
  pgdb 
  redis La conexión falla: error: no existe el rol «fvicente»
Se reintentará en la siguiente solicitud.

events.js:288
      throw er; // Unhandled 'error' event
      ^

error: no existe el rol «fvicente»
    at Connection.parseE (/home/fvicente/Proyectos/loopback4apps/new/marqfapp/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:581:48)
    at Connection.parseMessage (/home/fvicente/Proyectos/loopback4apps/new/marqfapp/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/home/fvicente/Proyectos/loopback4apps/new/marqfapp/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:116:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Emitted 'error' event on AuditdbDataSource instance at:
    at AuditdbDataSource.postInit (/home/fvicente/Proyectos/loopback4apps/new/marqfapp/node_modules/loopback-datasource-juggler/lib/datasource.js:502:16)
    at PendingItem.callback (/home/fvicente/Proyectos/loopback4apps/new/marqfapp/node_modules/loopback-connector-postgresql/lib/postgresql.js:102:17)
    at /home/fvicente/Proyectos/loopback4apps/new/marqfapp/node_modules/loopback-connector-postgresql/node_modules/pg-pool/index.js:237:23
    at Connection.connectingErrorHandler (/home/fvicente/Proyectos/loopback4apps/new/marqfapp/node_modules/loopback-connector-postgresql/node_modules/pg/lib/client.js:216:14)
    at Connection.emit (events.js:311:20)
    at Socket.<anonymous> (/home/fvicente/Proyectos/loopback4apps/new/marqfapp/node_modules/loopback-connector-postgresql/node_modules/pg/lib/connection.js:121:12)
    at Socket.emit (events.js:311:20)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'error',
  length: 99,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'miscinit.c',
  line: '607',
  routine: 'InitializeSessionUserId'
}

**Comment by IshuSF** [comment]
Hi @fgvicente 
The error is because of the Loopback CLI upgrade.
I have fixed the issue in the branch "[loopback_update](https://github.com/sourcefuse/loopback4-starter/tree/loopback_update)"
